### ISSUE TITLE
Specifying Logging (driver, options...) not showing up in generated Compose file

### ISSUE THREAD

**Issue by joshjones1980** [ironicbadger/ansible-role-docker-compose-generator#11]
Good day!
Thank you very much for this role, I have noticed a small problem though.
When I try to specify a logging configuration for a container, it never shows up in the output. Now, this very much could be a problem with my syntax and such, but I see no errors being thrown and everything else gets generated appropriately into the resulting Compose file.
Digging thru the template file, I can see where the loop exists to handle the logging settings, but they never trigger.

Example:
  - service_name: authelia
    container_name: authelia
    hostname: authelia
    image: authelia/authelia:4.32.2
    active: true
    volumes:
      - "{{ appdata_path }}/authelia:/config"
    restart: always
    include_global_env_vars: true
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

**Comment by coredotbin** [comment]
Hi Josh - Could you put your code in a code block (or indent each line with 4 spaces) as I'm not sure the indentation is coming through correctly in your issue.

**Comment by joshjones1980** [comment]
Sure thing, sorry about that - I see now that it definitely did not! 
Example:
`- service_name: authelia
    container_name: authelia
    hostname: authelia
    image: authelia/authelia:4.32.2
    active: true
    volumes:
      - "{{ appdata_path }}/authelia:/config"
    restart: always
    include_global_env_vars: true
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"`

Note: the preview for this is showing that my spacing is still not coming thru; suffice it to say that I'm including an image to show that the spacing is correct for everything else - and in fact when I run this, I do get a viable docker-compose.yml file; it simply 'skips' over the entire logging portion of the file.
"logging" is lined up with "restart" and "hostname" using spaces and not tabs. The "driver" and "options" lines have two additional spaces, and the "max-size" and "max-file" two more spaces beyond that.
<img width="347" alt="image" src="https://user-images.githubusercontent.com/5488688/187812747-6c412c4d-c101-44aa-93c9-ff5d7be35c7d.png">

**Comment by coredotbin** [comment]
Thanks Josh. Your syntax looks correct here. This is a newer feature - I'm wondering when you installed the role from Ansible Galaxy?

Could you post the output of
```
$ ansible-galaxy role info --offline ironicbadger.docker_compose_generator
```

**Comment by joshjones1980** [comment]
Let me start by saying that I feel sufficiently embarrassed at this point - it didn't occur to me that there might be an updated version of this. I re-pulled and there are definitely some differences - the chief one of my concern is that the "/templates/docker-compose.yml.j2" template file no longer contains the loop for 'logging' and such.

I will dig in some more - feels like I had some kind of delusion.

**Comment by joshjones1980** [comment]
Apologies, this is no longer an issue - apparently when I was pulling it in from Ansible Galaxy, it didn't have the logging loop that is in this repo.

All good now.
Thanks!!
