### ISSUE TITLE
Environment vars dont get created correctly when passed in the new format

### ISSUE THREAD

**Issue by boopzz** [IronicBadger/ansible-role-docker-compose-generator#2]
When passing environment vars in the format of:
```
environment:
  TZ: Europe/London
```
the output in the docker-compose appears as 
```
environment:
  - TZ
```
When passed in the older format of:
```
environment:
  - 'TZ=Europe/London'
```
The correct vars are created

**Comment by IronicBadger** [comment]
Both ways are acceptable according to the documentation for compose so I'm going to leave this as is.

https://docs.docker.com/compose/compose-file/compose-file-v3/#environment
