### ISSUE TITLE
"Containers is undefined" error

### ISSUE THREAD

**Issue by kimesz** [ironicbadger/ansible-role-docker-compose-generator#26]
The initial task to check the destination passes, but I receive the following error when Ansible tries to generate a docker compose file.

`TASK [ironicbadger.docker_compose_generator : write docker-compose file] ********************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible.errors.AnsibleUndefinedVariable: 'containers' is undefined. 'containers' is undefined
fatal: [192.168.110.10]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'containers' is undefined. 'containers' is undefined"}`

I am not sure why Ansible says containers is undefined. I double checked the syntax and indentation, which look okay. I  used your example to A/B test and receive the same error. 

I can send my playbook yaml and requirements yaml if that will be helpful.

Ansible: 2.14.4
Docker on remote host: 26.0.2
Docker compose on remote host: 2.26.1

**Comment by ironicbadger** [comment]
What's your YAML dict look like?
